INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('지하 2층에서 지하 1층까지 올라오는 \n 계단의 수는?', '20개', 'N', 'N', 'A');
INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('새로오신 주임 신부님의 \n 성함과 세례명은? ', '이종환 요셉', 'N', 'N', 'A');
INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('구의동 성당 설립 년월일은 ?', '1977.04.20', 'N', 'N', 'A');
INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('주임 신부님의 자동차는 무엇일까요?', '기아 프라이드 웨건 \n 97년식 수동', 'N', 'N', 'A');
INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('구의동성당 보안 업체는 무엇일까요?', '캡스', 'N', 'N', 'A');
INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('중고등부 담당 수녀님의 \n 세례명은 무엇일까요?', '마르티나', 'N', 'N', 'A');
INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('구의동성당 사무장님의 \n 세례명은 무엇일까요?', '소피아', 'N', 'N', 'B');
INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('제대 위 의자 개수는 몇 개 인가요? ', '9', 'N', 'N', 'B');
INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('우리 성당 로고의 의미는 무엇일까요? ', '그리스도의 부활', 'N', 'N', 'B');
INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('주일학교에 봉사단체는 몇개가 있을까요?', '3개 \n (성가대 봉사부 전례부)', 'N', 'N', 'B');
INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('부주임신부님의 축일은 언제일까요?', '6월 29일', 'N', 'N', 'B');
INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('오늘 날짜의 년, 월, 일을 곱하면?', '2023 * 10 * 28 = 566,440', 'N', 'N', 'B');
INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('성당 내 교리실은 몇 개인가요?', '12개', 'N', 'N', 'C');
INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('대성전 2층으로 가는 길은 몇 개인가요?', '2개', 'N', 'N', 'C');
INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('구의동 성당 후문 주차장 \n 파란색 분리수거 통은 몇 개인가요?', '5개', 'N', 'N', 'C');
INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('고해소의 개수는 몇 개인가요?', '2개', 'N', 'N', 'C');
INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('구의동 성당 주차장의 자리수는?', '35개', 'N', 'N', 'C');
INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('지하 2층의 여닫이 문은 모두 몇 개인가? \n (문짝 하나가 한 개) ', '14개', 'N', 'N', 'C');
INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('샬롬 광장의 나무 의자 다리 개수는? ', '72개', 'N', 'N', 'D');
INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('성당에 구비된 피아노와 오르간의 개수는? ', '5개', 'N', 'N', 'D');
INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('중고등부 미사에서 부르는 창미사곡의 \n 작곡가의 이름은?', '신상옥', 'N', 'N', 'D');
INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('대성전 십자가 옆 창문에 있는 \n 새는 무슨 새인가요?', '비둘기', 'N', 'N', 'D');
INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('대성전 십자가 옆 창문에 있는 \n 과일은 무엇인가요? ', '포도', 'N', 'N', 'D');
INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('대성당 쪽으로 내려가는 성당 입구에 있는 \n 계단의 개수는 ?', '7개', 'N', 'N', 'D');
INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('지하 2층 교사회합실 앞 사물함 색깔은?', '연노란색', 'N', 'N', 'E');
INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('마리아홀 문앞에 있는 동상은 누구일까요?', '성 김대건 \n 안드레아 신부님', 'N', 'N', 'E');
INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('성당 입구 우산꽃이통의 개수는 ? ', '11개', 'N', 'N', 'E');
INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('성모자상은 머리를 어느쪽으로 \n 기울이고 있나요? ', '(성모상을 바라보는 기준) \n 왼쪽', 'N', 'N', 'E');
INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('성당으로 내려오는 곳에 적혀있는 성구는?', '고생하며 무거운 짐을 진 \n 너희는 모두 나에게 오너라 \n 마태 11, 28', 'N', 'N', 'E');
INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('사제관의 위치는?', '성당 건물 3층', 'N', 'N', 'E');
INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('성당 건물 안으로 들어올 수 있는 \n 입구의 수는?', '3개', 'N', 'N', 'F');
INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('마르코 방은 어디 있을까요?', '마리아홀 들어가서 \n 왼쪽 방 3개중 가운데', 'N', 'N', 'F');
INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('대성전과 지하 2층 사이에 \n 직접 연결된 길이 있다?', 'O', 'N', 'N', 'F');
INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('지하 2층의 방 이름이 아닌 것은 ? \n (야고보, 토마스, 필립보, 마르타)', '마르타', 'N', 'N', 'F');
INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('샬롬 광장에 붙어 있는 주임 신부님 사진의 개수는? ', '12개', 'N', 'N', 'F');
INSERT INTO QUESTIONS (question, answer, use_yn, check_yn, type) values ('서울대교구 성당 설립계통도에 \n 설립 100년 이상 성당은 몇 개일까요?', '3개', 'N', 'N', 'F');

INSERT INTO TYPE_CHECK(type, q_num) values ('A', '');
INSERT INTO TYPE_CHECK(type, q_num) values ('B', '');
INSERT INTO TYPE_CHECK(type, q_num) values ('C', '');
INSERT INTO TYPE_CHECK(type, q_num) values ('D', '');
INSERT INTO TYPE_CHECK(type, q_num) values ('E', '');
INSERT INTO TYPE_CHECK(type, q_num) values ('F', '');